const express = require('express')

const { loadUserAccess, scopeUserAccess, excludeMobileSDK } = require('../middleware/auth')
const { maintenance: { isMaint } } = require('../middleware')

const map = require('./map')
const layer = require('./layer')
const whitelabel = require('./whitelabel')
const customer = require('./customer')
const builder = require('./builder')
const lift = require('./lift')
const poilist = require('./poilist')
const poi = require('./poi')
const report = require('./report')
const camp = require('./camp')
const aoi = require('./aoi')
const api = require('./api')
const expense = require('./expense')
const segments = require('./segments')
const market = require('./market')
const search = require('./search')
const loyaltyIndex = require('./loyalty-index')
const connections = require('./connections')
const geoQuery = require('./geo-query')
const widgets = require('./widgets')
const ql = require('./ml')
const weather = require('./weather')
const credentials = require('./credentials')
const log = require('./log')
const activity = require('./activity')
const dataset = require('./dataset')
const mobilesdk = require('./mobilesdk')
const usage = require('./usage')
const locussdk = require('./locussdk')
const facebook = require('./facebook')


const nonMobileSDKRouter = express.Router()
nonMobileSDKRouter.use(excludeMobileSDK)
nonMobileSDKRouter.use('/map', map)
nonMobileSDKRouter.use('/layer', layer)
nonMobileSDKRouter.use('/whitelabel', whitelabel)
nonMobileSDKRouter.use('/customer', customer)
nonMobileSDKRouter.use(['/builder', '/requests'], builder)
nonMobileSDKRouter.use('/lift', lift)
nonMobileSDKRouter.use('/poilist', poilist)
nonMobileSDKRouter.use('/poi', poi)
nonMobileSDKRouter.use('/report', report)
nonMobileSDKRouter.use('/camp', camp)
nonMobileSDKRouter.use('/aoi', aoi)
nonMobileSDKRouter.use('/expense', expense)
nonMobileSDKRouter.use('/segment', segments)
nonMobileSDKRouter.use('/market', market)
nonMobileSDKRouter.use('/search', search)
nonMobileSDKRouter.use('/loyalty(-index)?', loyaltyIndex)
nonMobileSDKRouter.use('/connections', connections)
nonMobileSDKRouter.use('/geoquery', geoQuery)
nonMobileSDKRouter.use('/widgets', widgets)
nonMobileSDKRouter.use(['/ql', '/ml'], ql)
nonMobileSDKRouter.use('/weather', weather)
nonMobileSDKRouter.use('/credentials', credentials)
nonMobileSDKRouter.use('/log', log)
nonMobileSDKRouter.use('/activity', activity)
nonMobileSDKRouter.use('/dataset', dataset)
nonMobileSDKRouter.use('/usage', usage)
nonMobileSDKRouter.use('/facebook', facebook)
nonMobileSDKRouter.use(api)

const rootRouter = express.Router()
rootRouter.use(isMaint)
rootRouter.use(loadUserAccess, scopeUserAccess)
rootRouter.use('/mobilesdk', mobilesdk)
rootRouter.use('/usage', usage)
rootRouter.use('/locussdk', locussdk)
rootRouter.use(api)
rootRouter.use(nonMobileSDKRouter)

module.exports = rootRouter
