const express = require('express')


const rootRouter = express.Router()
const { jwt } = require('../middleware/auth')
const { maintenance: { isMaint } } = require('../middleware')

const map = require('./map')
const layer = require('./layer')
const whitelabel = require('./whitelabel')
const customer = require('./customer')
const requests = require('./requests')
const lift = require('./lift')
const poilist = require('./poilist')
const poi = require('./poi')
const report = require('./report')
const camp = require('./camp')
const aoi = require('./aoi')
const api = require('./api')
const expense = require('./expense')
const segments = require('./segments')
const market = require('./market')
const search = require('./search')
const loyaltyIndex = require('./loyalty-index')
const connections = require('./connections')
const geoQuery = require('./geo-query')
const widgets = require('./widgets')
const ml = require('./ml')
const weather = require('./weather')
const credentials = require('./credentials')
const log = require('./log')
const activity = require('./activity')
const dataset = require('./dataset')


rootRouter.use(isMaint)
rootRouter.use(jwt)
rootRouter.use('/map', map)
rootRouter.use('/layer', layer)
rootRouter.use('/whitelabel', whitelabel)
rootRouter.use('/customer', customer)
rootRouter.use(['/requests', '/request(-approval)?'], requests)
rootRouter.use('/lift', lift)
rootRouter.use('/poilist', poilist)
rootRouter.use('/poi', poi)
rootRouter.use('/report', report)
rootRouter.use('/camp', camp)
rootRouter.use('/aoi', aoi)
rootRouter.use('/expense', expense)
rootRouter.use('/segment', segments)
rootRouter.use('/market', market)
rootRouter.use('/search', search)
rootRouter.use('/loyalty(-index)?', loyaltyIndex)
rootRouter.use('/connections', connections)
rootRouter.use('/geoquery', geoQuery)
rootRouter.use('/widgets', widgets)
rootRouter.use('/ml', ml)
rootRouter.use('/weather', weather)
rootRouter.use('/credentials', credentials)
rootRouter.use('/log', log)
rootRouter.use('/activity', activity)
rootRouter.use('/dataset', dataset)
rootRouter.use(api)


module.exports = rootRouter
