name: Serverless deployment - DEV stage

on:
  push:
    branches:
      - main
    tags:
      - 'dev-*'
    paths-ignore:
      - "README.md"

env:
  NODE_VERSION: 18.x
  DEPLOY_STAGE: dev

permissions:
  id-token: write   # This is required for requesting the JWT for step AWS Configure
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout designated tagged commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Node.js version and cache yarn dependencies
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install print-env
        run: python -m pip install print-env

      - name: Install serverless
        run:  npm install -g serverless

      - name: Install packages
        run: yarn install

      - name: Setup AWS CLI for "gh actions" user
        id: ghactions
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ vars.EQ_PROD_CD_LOCUS_QL_DEV_ROLE }}
          role-session-name: "${{ github.run_id }}-${{ github.sha }}"
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy
        run: yarn deploy --stage ${{ env.DEPLOY_STAGE }}
        env:
          # portunus token
          PORTUNUS_TOKEN: ${{ secrets.CD_PORTUNUS_ADMIN_JWT }}/${{ github.event.repository.name }}/${{ env.DEPLOY_STAGE }}
          # API version, passthrough
          API_VER: ${{ github.sha }}

      - name: Notify on deployment status
        if: ${{ always() }}
        run: npx @eqworks/notify deployment $GITHUB_REPOSITORY --commit=$GITHUB_SHA --stage=${{ env.DEPLOY_STAGE }} --status=$JOB_STATUS
        env:
          SLACK_HOOK: ${{ secrets.CD_SLACK_HOOK }}
          JOB_STATUS: ${{ job.status }}
