name: Serverless deployment - PROD stage

on:
  push:
    tags:
      - 'prod-*'

env:
  NODE_VERSION: 18.x
  DEPLOY_STAGE: prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout designated tagged commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Node.js version and cache yarn dependencies
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install print-env
        run: python -m pip install print-env

      - name: Install serverless
        run:  npm install -g serverless

      - name: Install packages
        run: yarn install

      - name: Deploy
        run: yarn deploy --stage ${{ env.DEPLOY_STAGE }}
        env:
          # aws creds for deployment
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          # portunus token
          PORTUNUS_TOKEN: ${{secrets.CD_PORTUNUS_TOKEN_JWT}}/${GITHUB_REPOSITORY##*/}/${{ env.DEPLOY_STAGE }}
          # API version, passthrough
          API_VER: ${{ github.sha }}

      - name: Notify on deployment status
        if: ${{ always() }}
        run: npx @eqworks/notify deployment $GITHUB_REPOSITORY --commit=$GITHUB_SHA --stage=${{ env.DEPLOY_STAGE }} --status=$JOB_STATUS
        env:
          SLACK_HOOK: ${{ secrets.CD_SLACK_HOOK }}
          JOB_STATUS: ${{ job.status }}

      - name: Generate tag associated release notes
        run: npx @eqworks/release notes -v --pattern="${{ env.DEPLOY_STAGE }}-*" --head ${GITHUB_REF##*/} --github
        env:
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify on release notes update
        if: ${{ success() }}
        run: npx @eqworks/notify send "Release notes updated for ${GITHUB_REPOSITORY} ${GITHUB_REF##*/}" --link "https://github.com/${GITHUB_REPOSITORY}/releases/tag/${GITHUB_REF##*/}" --status $JOB_STATUS
        env:
          SLACK_HOOK: ${{ secrets.CD_SLACK_HOOK }}
          JOB_STATUS: ${{ job.status }}
