name: Publish NPM package - alpha tag

on:
  push:
    tags:
      - 'v*-alpha*'

env:
  NODE_VERSION: 18.x
  DIST_TAG: alpha

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout designated tagged commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Node.js version and .npmrc file to publish to GitHub Packages
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          registry-url: https://npm.pkg.github.com/
          scope: '@eqworks'
          always-auth: true

      - name: Install packages
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CD_GITHUB_TOKEN }}

      - name: Publishing packages to the npm registry
        run: yarn publish --tag ${{ env.DIST_TAG }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Node.js version and .npmrc file to publish to npm
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
          scope: '@eqworks'
          always-auth: true

      - name: Publishing packages to GitHub Packages
        run: yarn publish --tag ${{ env.DIST_TAG }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CD_NPM_TOKEN_PUBLISH }}
